const express = require("express");
const controller = require("../controllers/admin");
const { rolesRequired } = require("../middleware/auth");
const router = express.Router();
const admin = rolesRequired("admin");
router.use("/admin", admin);
router.post("/admin/clear-data", controller.clearData);
router.post("/admin/truncate-data", (req, res) => controller.clearData(req, res, true));
router.post("/admin/reset-data", controller.clearData);
router.post("/admin/reset-db", controller.resetDb);
router.get("/admin/migration/status", controller.migrationStatus);
router.post("/admin/migration/upgrade", controller.migrationUpgrade);
router.post("/admin/migration/downgrade", controller.migrationDowngrade);
router.post("/admin/seed-admin", controller.seedAdmin);
router.get("/admin/db-status", controller.dbStatus);
router.get("/admin/analytics", controller.analytics);
router.get("/admin/users", controller.listUsers);
router.get("/admin/users/test-candidates", controller.testCandidates);
router.post("/admin/users/bulk-export", controller.csv);
router.get("/admin/users/:user_id", controller.getUser);
router.post("/admin/users/:user_id/toggle-suspend", controller.toggleSuspend);
router.patch("/admin/users/:user_id/status", controller.updateStatus);
router.post("/admin/users/:user_id/force-logout", controller.forceLogout);
router.post("/admin/users/:user_id/request-delete", controller.requestDelete);
router.patch("/admin/users/:user_id/test-account", controller.toggleTest);
router.get("/admin/export/:report_type", controller.exportReport);
router.get("/admin/privacy/requests", controller.listPrivacy);
router.post("/admin/privacy/requests/:request_id/complete", controller.completePrivacy);
router.get("/admin/privacy/integrations", controller.integrations);
router.get("/admin/privacy/consents/:user_id", controller.consents);
module.exports = router;
