const { AIHealthAssistantSession, CycleHistoryLog, CustomTag, DailyLog, HealthProfile, MedicationSupplementReminder, PCOSDisorderStatus, PerimenopauseLog, PregnancyProfile, PushSubscription, SymptomTrackingLog, Subscription, UserConsent, UserProfile, WearableConnection } = require("../models");
const { createPrivacyRequest, recordConsent } = require("../services/privacy");
const { addDays, dateOnly, diffDays, parseDateOnly } = require("../utils/dates");
const { errorResponse, messageResponse, validationErrors } = require("../utils/response");
const { publicUser, serialize } = require("../utils/serialize");
const { config } = require("../config/env");

async function accountExport(req, res) {
  await createPrivacyRequest(req.user, "export");
  const health = await HealthProfile.findOne({ profile_id: req.user.id });
  const [cycles, symptoms, dailyLogs, reminders, tags, periLogs, pregnancy, sessions, pcosStatuses] = await Promise.all([
    CycleHistoryLog.find({ profile_id: req.user.id }), SymptomTrackingLog.find({ profile_id: req.user.id }), DailyLog.find({ profile_id: req.user.id }), MedicationSupplementReminder.find({ profile_id: req.user.id }), CustomTag.find({ profile_id: req.user.id }), PerimenopauseLog.find({ profile_id: req.user.id }), PregnancyProfile.findOne({ profile_id: req.user.id }), AIHealthAssistantSession.find({ profile_id: req.user.id }), health ? PCOSDisorderStatus.find({ health_profile_id: health.id }) : [],
  ]);
  const payload = { user: publicUser(req.user), health_profile: health ? serialize(health, ["last_period_start", "last_notified_for", "created_at", "updated_at"]) : null, pcos_statuses: pcosStatuses.map((item) => serialize(item, ["diagnosed_date", "created_at"])), cycle_history_logs: cycles.map((item) => serialize(item, ["cycle_start_date", "cycle_end_date", "predicted_next_period_date", "created_at"])), symptom_tracking_logs: symptoms.map((item) => serialize(item, ["date_time", "created_at"])), daily_logs: dailyLogs.map((item) => serialize(item, ["log_date", "created_at", "updated_at"])), medication_reminders: reminders.map((item) => serialize(item, ["adherence_date", "last_push_sent_on", "created_at"])), custom_tags: tags.map((item) => serialize(item, ["created_at"])), perimenopause_logs: periLogs.map((item) => serialize(item, ["log_date", "created_at"])), pregnancy_profile: pregnancy ? serialize(pregnancy, ["last_menstrual_period", "due_date", "created_at", "updated_at"]) : null, ai_sessions: sessions.map((item) => serialize(item, ["created_at", "updated_at"])) };
  return res.type("application/json").set("Content-Disposition", 'attachment; filename="penmozhi-export.json"').send(JSON.stringify(payload, null, 2));
}

async function getPregnancy(req, res) { const row = await PregnancyProfile.findOne({ profile_id: req.user.id }); return res.json({ pregnancy_profile: row ? serialize(row, ["last_menstrual_period", "due_date", "created_at", "updated_at"]) : null }); }
async function updatePregnancy(req, res) { const lmp = parseDateOnly(req.body?.last_menstrual_period); if (!lmp) return validationErrors(res, [["validation.invalid_payload", "last_menstrual_period must be a valid date."]]); let row = await PregnancyProfile.findOne({ profile_id: req.user.id }); if (!row) row = new PregnancyProfile({ profile_id: req.user.id }); const weeks = Math.floor(diffDays(new Date(), lmp) / 7); Object.assign(row, { last_menstrual_period: lmp, due_date: addDays(lmp, 280), current_trimester: weeks < 13 ? 1 : weeks < 27 ? 2 : 3, updated_at: new Date() }); await row.save(); return messageResponse(res, "pregnancy_profile.updated_success", "Pregnancy profile updated successfully.", 200, { pregnancy_profile: serialize(row, ["last_menstrual_period", "due_date", "created_at", "updated_at"]) }); }

async function createPerimenopause(req, res) { const date = parseDateOnly(req.body?.log_date); if (!date) return validationErrors(res, [["validation.invalid_payload", "log_date must be a valid date."]]); if (await PerimenopauseLog.exists({ profile_id: req.user.id, log_date: date })) return validationErrors(res, [["validation.log_date_exists", "A log already exists for this date."]]); const row = await PerimenopauseLog.create({ profile_id: req.user.id, log_date: date, hot_flashes: Boolean(req.body.hot_flashes), night_sweats: Boolean(req.body.night_sweats), mood_changes: req.body.mood_changes || null, sleep_disruption: Boolean(req.body.sleep_disruption), notes: req.body.notes || null }); return messageResponse(res, "perimenopause_logs.created_success", "Perimenopause log created successfully.", 201, { perimenopause_log: serialize(row, ["log_date", "created_at"]) }); }
async function getPerimenopause(req, res) { const query = { profile_id: req.user.id }; if (req.query.from) query.log_date = { $gte: parseDateOnly(req.query.from) }; if (req.query.to) query.log_date = { ...(query.log_date || {}), $lte: parseDateOnly(req.query.to) }; const rows = await PerimenopauseLog.find(query).sort({ log_date: -1 }); return res.json({ perimenopause_logs: rows.map((item) => serialize(item, ["log_date", "created_at"])) }); }
async function updatePerimenopause(req, res) { const row = await PerimenopauseLog.findOne({ id: Number(req.params.log_id), profile_id: req.user.id }); if (!row) return errorResponse(res, "perimenopause_logs.not_found", "Perimenopause log not found.", 404); for (const field of ["hot_flashes", "night_sweats", "mood_changes", "sleep_disruption", "notes"]) if (req.body[field] !== undefined) row[field] = req.body[field]; if (req.body.log_date) row.log_date = parseDateOnly(req.body.log_date); await row.save(); return messageResponse(res, "perimenopause_logs.updated_success", "Perimenopause log updated successfully.", 200, { perimenopause_log: serialize(row, ["log_date", "created_at"]) }); }

async function myPcos(req, res) { const health = await HealthProfile.findOne({ profile_id: req.user.id }); if (!health) return errorResponse(res, "health.not_found", "Health profile not found.", 404); const rows = await PCOSDisorderStatus.find({ health_profile_id: health.id }).sort({ created_at: -1 }); return res.json({ pcos_statuses: rows.map((item) => serialize(item, ["diagnosed_date", "created_at"])) }); }
async function updatePcos(req, res) { const current = await PCOSDisorderStatus.findOne({ id: Number(req.params.status_id) }); if (!current) return errorResponse(res, "pcos.not_found", "PCOS disorder status not found.", 404); const health = await HealthProfile.findOne({ id: current.health_profile_id, profile_id: req.user.id }); if (!health) return errorResponse(res, "auth.forbidden", "Access forbidden: insufficient permissions.", 403); const row = await PCOSDisorderStatus.create({ health_profile_id: current.health_profile_id, disorder_type: req.body.disorder_type ?? current.disorder_type, diagnosis_status: req.body.diagnosis_status ?? current.diagnosis_status, diagnosed_date: req.body.diagnosed_date ? parseDateOnly(req.body.diagnosed_date) : current.diagnosed_date }); return messageResponse(res, "pcos.updated_success", "PCOS disorder status updated successfully.", 200, { pcos_status: serialize(row, ["diagnosed_date", "created_at"]) }); }
async function pcosHistory(req, res) { const current = await PCOSDisorderStatus.findOne({ id: Number(req.params.status_id) }); if (!current) return errorResponse(res, "pcos.not_found", "PCOS disorder status not found.", 404); const health = await HealthProfile.findOne({ id: current.health_profile_id, profile_id: req.user.id }); if (!health) return errorResponse(res, "auth.forbidden", "Access forbidden: insufficient permissions.", 403); const rows = await PCOSDisorderStatus.find({ health_profile_id: health.id }).sort({ created_at: -1 }); return res.json({ pcos_status: serialize(current, ["diagnosed_date", "created_at"]), history: rows.map((item) => serialize(item, ["diagnosed_date", "created_at"])) }); }
async function pcosPatterns(req, res) { const [cycles, symptoms] = await Promise.all([CycleHistoryLog.find({ profile_id: req.user.id }).lean(), SymptomTrackingLog.find({ profile_id: req.user.id }).lean()]); const patterns = []; if (cycles.some((cycle, index) => index > 0 && diffDays(cycle.cycle_start_date, cycles[index - 1].cycle_start_date) > 45)) patterns.push({ pattern: "irregular_cycles", description: "Some logged cycle gaps are longer than the typical range.", triggered_logs: { cycles } }); if (symptoms.filter((item) => item.category === "acne").length >= 2) patterns.push({ pattern: "acne_symptoms", description: "Repeated acne symptoms were found in your logs.", triggered_logs: { symptoms } }); return res.json({ patterns, disclaimer: "These patterns are not a diagnosis. Please discuss health concerns with a qualified clinician.", analyzed_at: new Date().toISOString() }); }

async function createPush(req, res) { const data = req.body || {}; if (!["endpoint", "p256dh", "auth"].every((key) => String(data[key] || "").trim())) return validationErrors(res, [["validation.invalid_payload", "endpoint, p256dh, and auth are required."]]); let row = await PushSubscription.findOne({ endpoint: String(data.endpoint).trim() }); if (!row) row = new PushSubscription({ endpoint: String(data.endpoint).trim() }); Object.assign(row, { profile_id: req.user.id, p256dh: String(data.p256dh).trim(), auth: String(data.auth).trim(), device_type: data.device_type || null }); await row.save(); return messageResponse(res, "push_subscriptions.created_success", "Push subscription registered successfully.", 201, { push_subscription: serialize(row, ["created_at"]) }); }
async function deletePush(req, res) { const row = await PushSubscription.findOne({ id: Number(req.params.subscription_id), profile_id: req.user.id }); if (!row) return errorResponse(res, "push_subscriptions.not_found", "Push subscription not found.", 404); await row.deleteOne(); return messageResponse(res, "push_subscriptions.deleted_success", "Push subscription removed successfully."); }
async function unsubscribePush(req, res) { const endpoint = String(req.body?.endpoint || "").trim(); if (!endpoint) return validationErrors(res, [["validation.invalid_payload", "endpoint is required."]]); await PushSubscription.deleteMany({ profile_id: req.user.id, endpoint }); return messageResponse(res, "push_subscriptions.deleted_success", "Push subscription removed successfully."); }

const PROVIDERS = ["oura", "whoop", "fitbit", "withings", "garmin", "apple"];
async function wearables(req, res) { const rows = await WearableConnection.find({ profile_id: req.user.id }).sort({ provider: 1 }); return res.json({ wearable_connections: rows.map((item) => serialize(item, ["last_synced_at", "created_at"])) }); }
function validProvider(provider) { return PROVIDERS.includes(String(provider).toLowerCase().trim()); }
async function connectWearable(req, res) { const provider = String(req.params.provider).toLowerCase().trim(); if (!validProvider(provider)) return errorResponse(res, "wearables.invalid_provider", "Unsupported wearable provider.", 400); return res.json({ message: "Wearable OAuth is not yet configured.", message_code: "wearables.oauth_stub", provider, redirect_url: `${config.clientAppUrl.replace(/\/$/, "")}/dashboard/wearables?provider=${provider}&status=stub`, todo: `Configure ${provider.toUpperCase()}_CLIENT_ID and ${provider.toUpperCase()}_CLIENT_SECRET and implement OAuth authorization URL generation.` }); }
async function callbackWearable(req, res) { const provider = String(req.params.provider).toLowerCase().trim(); if (!validProvider(provider)) return errorResponse(res, "wearables.invalid_provider", "Unsupported wearable provider.", 400); if (!req.query.code) return errorResponse(res, "wearables.missing_code", "Authorization code missing.", 400); let row = await WearableConnection.findOne({ profile_id: req.user.id, provider }); if (!row) row = new WearableConnection({ profile_id: req.user.id, provider }); row.access_token = `stub_access_${String(req.query.code).slice(0, 8)}`; row.refresh_token = `stub_refresh_${String(req.query.code).slice(0, 8)}`; row.last_synced_at = new Date(); await row.save(); await recordConsent(req.user.id, "wearable_data_sharing", provider); return res.redirect(`${config.clientAppUrl.replace(/\/$/, "")}/dashboard/wearables?provider=${provider}&status=connected`); }
async function disconnectWearable(req, res) { const provider = String(req.params.provider).toLowerCase().trim(); const row = await WearableConnection.findOne({ profile_id: req.user.id, provider }); if (!row) return errorResponse(res, "wearables.not_found", "Wearable connection not found.", 404); await row.deleteOne(); return messageResponse(res, "wearables.disconnected_success", "Wearable disconnected successfully."); }

async function subscription(req, res) { const row = await Subscription.findOne({ profile_id: req.user.id }); return res.json({ subscription: row ? serialize(row, ["current_period_end", "created_at"]) : { plan: "free", status: "active", current_period_end: null } }); }
async function checkout(req, res) { let row = await Subscription.findOne({ profile_id: req.user.id }); if (!row) row = new Subscription({ profile_id: req.user.id }); row.plan = ["free", "plus"].includes(String(req.body?.plan).toLowerCase()) ? String(req.body.plan).toLowerCase() : "plus"; row.status = "pending_payment"; await row.save(); return res.json({ message: "Checkout stub — payment integration pending.", message_code: "subscriptions.checkout_stub", checkout_url: null, subscription: serialize(row, ["current_period_end", "created_at"]), todo: "Implement real payment checkout session and redirect URL." }); }
async function webhook(req, res) { return res.json({ message: "Webhook received (stub).", message_code: "subscriptions.webhook_stub", received: req.body || {}, todo: "Implement payment webhook verification and subscription lifecycle updates." }); }

async function insights(req, res) { const cycleInsights = await require("../services/cyclePrediction").computeCycleInsights(req.user); const [cycles, daily, symptoms] = await Promise.all([CycleHistoryLog.find({ profile_id: req.user.id }).lean(), DailyLog.find({ profile_id: req.user.id }).lean(), SymptomTrackingLog.find({ profile_id: req.user.id }).lean()]); return res.json({ months: Number(req.query.months || 6), has_cycle_data: cycles.length > 0, has_daily_log_data: daily.length > 0, has_symptom_data: symptoms.length > 0, cycle_statistics: cycleInsights.statistics, cycle_length_trend: [], period_length_trend: [], symptom_trends: { date_trends: [], category_trends: [], total_entries: symptoms.length }, daily_pain_trend: daily.filter((item) => item.pain_level).map((item) => ({ date: dateOnly(item.log_date), score: Number(item.pain_level) || 0, level: item.pain_level })), sleep_trend: daily.filter((item) => item.sleep_hours !== null && item.sleep_hours !== undefined).map((item) => ({ date: dateOnly(item.log_date), hours: item.sleep_hours })), energy_trend: [], mood_frequency: [], mood_timeline: [], total_daily_logs: daily.length }); }

module.exports = { accountExport, callbackWearable, checkout, connectWearable, createPerimenopause, createPush, deletePush, deleteTag: undefined, disconnectWearable, getPerimenopause, getPregnancy, getReminders: undefined, getPush: undefined, insights, myPcos, pcosHistory, pcosPatterns, subscription, unsubscribePush, updatePcos, updatePerimenopause, updatePregnancy, wearables, webhook };
