const { AdminActionLog, AIHealthAssistantSession, Counter, PrivacyRequest, PushSubscription, Subscription, UserConsent, UserProfile, WearableConnection } = require("../models");
const { config } = require("../config/db");
const { createPrivacyRequest, deleteUserAccount } = require("../services/privacy");
const { hashPassword } = require("../utils/password");
const { publicUser, serialize } = require("../utils/serialize");
const { errorResponse, validationErrors } = require("../utils/response");
const mongoose = require("mongoose");

async function log(adminId, action, targetUserId = null, notes = null) { await AdminActionLog.create({ admin_id: adminId, action_type: action, target_user_id: targetUserId, notes }); }
function userDetail(user) { return publicUser(user); }
async function getTarget(id) { return UserProfile.findOne({ id: Number(id), role: "user" }); }

async function clearData(req, res, truncate = false) { const models = require("../models"); const deletedCounts = {}; for (const [name, Model] of Object.entries(models)) if (name !== "Counter" && typeof Model.deleteMany === "function") { const result = await Model.deleteMany({}); deletedCounts[Model.collection.name] = result.deletedCount || 0; } await log(req.user.id, truncate ? "truncate-data" : "clear-data"); return res.json({ success: true, operation: truncate ? "truncate-data" : "clear-data", message: truncate ? "All application collections truncated. New records will start from id=1." : "All application data deleted. AUTO_INCREMENT values were not reset.", ids_reset: truncate, deleted_counts: deletedCounts }); }
async function resetDb(req, res) { if (config.nodeEnv === "production") return res.status(403).json({ success: false, error: "Reset database is only available in development mode." }); await clearData(req, res, true); await Counter.deleteMany({}); }
async function migrationStatus(req, res) { await log(req.user.id, "migration-status"); return res.json({ success: true, operation: "migration-status", current_revision: "mongodb", head_revision: "mongodb", pending_upgrade: false, pending_revisions: [] }); }
async function migrationUpgrade(req, res) { await log(req.user.id, "migration-upgrade"); return res.json({ success: true, operation: "migration-upgrade", message: "MongoDB schema uses application-managed indexes; no migrations are pending.", current_revision: "mongodb", head_revision: "mongodb", pending_upgrade: false, pending_revisions: [] }); }
async function migrationDowngrade(req, res) { if (config.nodeEnv !== "development") return res.status(403).json({ success: false, error: "Migration downgrade is only available in development mode." }); return migrationUpgrade(req, res); }
async function seedAdmin(req, res) { if (!config.adminName || !config.adminEmail || !config.adminPassword) return res.status(400).json({ success: false, error: "Missing required environment variables.", missing: [!config.adminName && "ADMIN_NAME", !config.adminEmail && "ADMIN_EMAIL", !config.adminPassword && "ADMIN_PASSWORD"].filter(Boolean) }); let admin = await UserProfile.findOne({ email: config.adminEmail.trim().toLowerCase() }); if (admin) return res.json({ success: true, message: "Admin account already exists.", created: false, admin: publicUser(admin) }); admin = await UserProfile.create({ full_name: config.adminName.trim(), date_of_birth: new Date("1990-01-01"), email: config.adminEmail.trim().toLowerCase(), password_hash: await hashPassword(config.adminPassword), language_preference: "english", role: "admin", onboarding_completed: true }); return res.status(201).json({ success: true, message: "Admin account created successfully.", created: true, admin: publicUser(admin) }); }
async function dbStatus(req, res) { const models = require("../models"); const counts = {}; let total = 0; for (const [name, Model] of Object.entries(models)) if (name !== "Counter" && typeof Model.countDocuments === "function") { const count = await Model.countDocuments(); counts[Model.collection.name] = count; total += count; } await log(req.user.id, "db-status"); return res.json({ success: true, health_status: mongoose.connection.readyState === 1 ? "healthy" : "unhealthy", total_tables: Object.keys(counts).length, application_tables: Object.keys(counts).length, total_records: total, table_counts: counts, current_revision: "mongodb", head_revision: "mongodb", pending_upgrade: false, pending_revisions: [] }); }
async function analytics(req, res) { const [users, admins, onboarded, sessions] = await Promise.all([UserProfile.countDocuments({ role: "user" }), UserProfile.countDocuments({ role: "admin" }), UserProfile.countDocuments({ role: "user", onboarding_completed: true }), AIHealthAssistantSession.distinct("profile_id")]); return res.json({ period_days: Number(req.query.days || 30), total_users: users, total_admins: admins, onboarding_completed: onboarded, onboarding_pending: users - onboarded, ai_users: sessions.length }); }
async function listUsers(req, res) { const page = Math.max(1, Number(req.query.page || 1)); const perPage = Math.min(Math.max(1, Number(req.query.per_page || 20)), 100); const query = { role: "user" }; if (req.query.search) query.$or = [{ email: { $regex: String(req.query.search), $options: "i" } }, { full_name: { $regex: String(req.query.search), $options: "i" } }]; if (req.query.status && req.query.status !== "all") query.status = req.query.status; if (req.query.onboarding === "complete") query.onboarding_completed = true; if (req.query.onboarding === "pending") query.onboarding_completed = false; if (String(req.query.hide_test_accounts ?? "true") !== "false") query.is_test_account = false; const [users, total] = await Promise.all([UserProfile.find(query).sort({ registration_date: -1 }).skip((page - 1) * perPage).limit(perPage), UserProfile.countDocuments(query)]); return res.json({ users: users.map(userDetail), pagination: { page, per_page: perPage, total, pages: Math.ceil(total / perPage) } }); }
async function getUser(req, res) { const user = await getTarget(req.params.user_id); if (!user) return errorResponse(res, "admin.user_not_found", "User not found.", 404); const sub = await Subscription.findOne({ profile_id: user.id }); const [consents, actions] = await Promise.all([UserConsent.find({ user_id: user.id }).sort({ granted_at: -1 }), AdminActionLog.find({ target_user_id: user.id }).sort({ timestamp: -1 })]); await log(req.user.id, "view", user.id); return res.json({ user: userDetail(user), subscription: { plan: sub?.plan || "free", status: sub?.status || "active", label: sub?.plan === "plus" ? "Plus" : "Free", current_period_end: sub?.current_period_end?.toISOString() || null, created_at: sub?.created_at?.toISOString() || null }, payment_history: { implemented: false, message: "PayHere payment history is not implemented yet.", records: [] }, activity: { last_active_at: user.last_active_at?.toISOString() || null, login_count: user.login_count, onboarding_completed: user.onboarding_completed }, consents: consents.map((item) => serialize(item, ["granted_at"])), admin_action_logs: actions.map((item) => serialize(item, ["timestamp"])) }); }
async function toggleSuspend(req, res) { const user = await getTarget(req.params.user_id); if (!user) return errorResponse(res, "admin.user_not_found", "User not found.", 404); if (user.status === "banned") return validationErrors(res, [["admin.user_banned", "Banned users must be unbanned from the detail page."]]); user.status = user.status === "active" ? "suspended" : "active"; await user.save(); await log(req.user.id, user.status === "suspended" ? "suspend" : "unsuspend", user.id); return res.json({ message: "User status updated.", user: userDetail(user) }); }
async function updateStatus(req, res) { const user = await getTarget(req.params.user_id); if (!user) return errorResponse(res, "admin.user_not_found", "User not found.", 404); if (!["active", "suspended", "banned"].includes(req.body?.status)) return validationErrors(res, [["validation.status_invalid", "status must be active, suspended, or banned."]]); user.status = req.body.status; await user.save(); await log(req.user.id, "update_status", user.id, req.body.status); return res.json({ message: "User status updated.", user: userDetail(user) }); }
async function forceLogout(req, res) { const user = await getTarget(req.params.user_id); if (!user) return errorResponse(res, "admin.user_not_found", "User not found.", 404); user.token_valid_after = new Date(); await user.save(); await log(req.user.id, "force_logout", user.id); return res.json({ message: "All active sessions have been invalidated." }); }
async function requestDelete(req, res) { const user = await getTarget(req.params.user_id); if (!user) return errorResponse(res, "admin.user_not_found", "User not found.", 404); const requestRow = await createPrivacyRequest(user, "delete"); await log(req.user.id, "request_delete", user.id, `PrivacyRequest id=${requestRow.id}`); return res.status(201).json({ message: "Deletion request created. Complete it from Privacy & Compliance.", privacy_request_id: requestRow.id, redirect_path: "/admin/privacy" }); }
async function toggleTest(req, res) { const user = await getTarget(req.params.user_id); if (!user) return errorResponse(res, "admin.user_not_found", "User not found.", 404); user.is_test_account = req.body?.is_test_account === undefined ? !user.is_test_account : Boolean(req.body.is_test_account); await user.save(); await log(req.user.id, user.is_test_account ? "mark_test_account" : "unmark_test_account", user.id); return res.json({ message: "Test account flag updated.", user: userDetail(user) }); }
async function testCandidates(req, res) { const candidates = await UserProfile.find({ role: "user", is_test_account: false, $or: [{ email: { $regex: "test", $options: "i" } }, { email: { $regex: "example", $options: "i" } }] }).limit(100); return res.json({ candidates: candidates.map(userDetail) }); }
async function csv(req, res) { const users = req.body?.user_ids ? await UserProfile.find({ id: { $in: req.body.user_ids.map(Number) }, role: "user" }).sort({ id: 1 }) : await UserProfile.find({ role: "user" }).sort({ id: 1 }); const lines = ["id,full_name,email,status,subscription", ...users.map((user) => `${user.id},"${String(user.full_name).replaceAll('"', '""')}",${user.email},${user.status},free`)]; res.type("text/csv").set("Content-Disposition", 'attachment; filename="penmozhi-users.csv"').send(lines.join("\n")); }
async function exportReport(req, res) { if (req.params.report_type !== "users") return errorResponse(res, "admin.invalid_report", "Unknown report type.", 400); return csv(req, res); }
async function listPrivacy(req, res) { const query = req.query.status ? { status: String(req.query.status).toLowerCase() } : {}; const rows = await PrivacyRequest.find(query).sort({ created_at: -1 }); return res.json({ privacy_requests: rows.map((item) => serialize(item, ["created_at", "completed_at"])) }); }
async function completePrivacy(req, res) { const row = await PrivacyRequest.findOne({ id: Number(req.params.request_id) }); if (!row) return errorResponse(res, "privacy.request_not_found", "Privacy request not found.", 404); if (row.status === "completed") return errorResponse(res, "privacy.already_completed", "This request is already completed.", 409); if (row.request_type === "delete" && row.user_id) { await deleteUserAccount(row.user_id); row.user_id = null; } row.status = "completed"; row.completed_at = new Date(); row.completed_by_admin_id = req.user.id; await row.save(); return res.json({ message: "Privacy request marked as completed.", privacy_request: serialize(row, ["created_at", "completed_at"]), deletion_approach: "hard_delete", tables_affected: ["user_profiles", "health_profiles", "cycle_history_logs", "daily_logs", "symptom_tracking_logs", "medication_supplement_reminders", "ai_health_assistant_sessions"] }); }
async function integrations(req, res) { const [wearables, push, ai] = await Promise.all([WearableConnection.aggregate([{ $group: { _id: "$provider", count: { $sum: 1 } } }]), PushSubscription.countDocuments(), AIHealthAssistantSession.distinct("profile_id")]); const counts = Object.fromEntries(wearables.map((item) => [item._id, item.count])); const catalog = [{ provider: "oura", integration_type: "wearable", data_categories: ["sleep duration", "heart rate", "activity levels", "readiness scores"] }, { provider: "whoop", integration_type: "wearable", data_categories: ["strain", "recovery", "sleep performance", "heart rate variability"] }, { provider: "fitbit", integration_type: "wearable", data_categories: ["steps", "sleep", "heart rate", "activity"] }, { provider: "withings", integration_type: "wearable", data_categories: ["weight", "sleep", "heart rate", "activity"] }, { provider: "garmin", integration_type: "wearable", data_categories: ["activity", "sleep", "heart rate", "stress"] }, { provider: "apple", integration_type: "wearable", data_categories: ["activity", "sleep", "heart rate", "cycle data (HealthKit)"] }, { provider: "web_push", integration_type: "notifications", data_categories: ["device push tokens", "notification delivery metadata"] }, { provider: "google_gemini", integration_type: "ai_processing", data_categories: ["anonymized health context snippets", "AI assistant chat messages"] }, { provider: "anthropic", integration_type: "ai_processing", data_categories: ["anonymized health context snippets", "AI assistant chat messages"] }]; return res.json({ integrations: catalog.map((item) => ({ ...item, connected_users: item.provider === "web_push" ? push : ["google_gemini", "anthropic"].includes(item.provider) ? ai.length : counts[item.provider] || 0, status: ["google_gemini", "anthropic"].includes(item.provider) || counts[item.provider] || push ? "active" : "available" })) }); }
async function consents(req, res) { const user = await UserProfile.findOne({ id: Number(req.params.user_id) }); if (!user) return errorResponse(res, "auth.user_not_found", "User not found.", 404); const rows = await UserConsent.find({ user_id: user.id }).sort({ granted_at: -1 }); return res.json({ user_id: user.id, user_email: user.email, consents: rows.map((item) => serialize(item, ["granted_at"])) }); }

module.exports = { analytics, clearData, completePrivacy, consents, csv, dbStatus, exportReport, forceLogout, getUser, integrations, listPrivacy, listUsers, migrationDowngrade, migrationStatus, migrationUpgrade, requestDelete, resetDb, seedAdmin, testCandidates, toggleStatus: toggleSuspend, toggleSuspend, toggleTest, updateStatus };
