const crypto = require("node:crypto");
const { EducationalResource, EducationVideo, ForumComment, ForumPost } = require("../models");
const { config } = require("../config/db");
const { dateOnly, parseDateOnly } = require("../utils/dates");
const { errorResponse, messageResponse, validationErrors } = require("../utils/response");
const { serialize } = require("../utils/serialize");

function language(value) { const normalized = String(value || "").trim().toLowerCase(); return normalized === "en" ? "english" : normalized === "ta" ? "tamil" : ["english", "tamil"].includes(normalized) ? normalized : null; }
function publicVideo(video, includeUrl = false, admin = false) { const result = serialize(video, ["created_at", "updated_at"]); if (!includeUrl) delete result.video_url; if (admin) { result.video_public_id = video.video_public_id; result.created_by_admin_id = video.created_by_admin_id; } return result; }

async function listEducation(req, res) { const query = {}; if (req.query.category) query.content_category = String(req.query.category).trim(); const lang = language(req.query.language); if (lang) query.language = lang; const rows = await EducationalResource.find(query).sort({ publication_date: -1 }); return res.json({ education_resources: rows.map((item) => serialize(item, ["publication_date", "created_at"])) }); }
async function getEducation(req, res) { const row = await EducationalResource.findOne({ id: Number(req.params.resource_id) }); if (!row) return errorResponse(res, "education.not_found", "Educational resource not found.", 404); return res.json({ education_resource: serialize(row, ["publication_date", "created_at"]) }); }
async function createEducation(req, res) { const data = req.body || {}; const errors = ["article_title", "content_category", "content_body", "publication_date"].filter((key) => !String(data[key] || "").trim()).map((key) => `${key} is required.`); if (!parseDateOnly(data.publication_date)) errors.push("publication_date must be a valid date (YYYY-MM-DD)."); if (data.language && !language(data.language)) errors.push("language must be 'english' or 'tamil'."); if (errors.length) return validationErrors(res, errors.map((message) => ["validation.invalid_payload", message])); const row = await EducationalResource.create({ article_title: String(data.article_title).trim(), content_category: String(data.content_category).trim(), content_body: String(data.content_body).trim(), language: language(data.language) || "english", publication_date: parseDateOnly(data.publication_date) }); return messageResponse(res, "education.created_success", "Educational resource created successfully.", 201, { education_resource: serialize(row, ["publication_date", "created_at"]) }); }
async function updateEducation(req, res) { const row = await EducationalResource.findOne({ id: Number(req.params.resource_id) }); if (!row) return errorResponse(res, "education.not_found", "Educational resource not found.", 404); for (const key of ["article_title", "content_category", "content_body"]) if (req.body[key] !== undefined) row[key] = String(req.body[key]).trim(); if (req.body.language) row.language = language(req.body.language) || row.language; if (req.body.publication_date) row.publication_date = parseDateOnly(req.body.publication_date); await row.save(); return messageResponse(res, "education.updated_success", "Educational resource updated successfully.", 200, { education_resource: serialize(row, ["publication_date", "created_at"]) }); }
async function deleteEducation(req, res) { const row = await EducationalResource.findOne({ id: Number(req.params.resource_id) }); if (!row) return errorResponse(res, "education.not_found", "Educational resource not found.", 404); await row.deleteOne(); return messageResponse(res, "education.deleted_success", "Educational resource deleted successfully."); }

async function listVideos(req, res) { const query = req.query.category ? { category: String(req.query.category).trim() } : {}; const rows = await EducationVideo.find(query).sort({ created_at: -1 }); return res.json({ education_videos: rows.map((item) => publicVideo(item, false)) }); }
async function getVideo(req, res) { const row = await EducationVideo.findOne({ id: Number(req.params.video_id) }); if (!row) return errorResponse(res, "education.video_entry_not_found", "Education video not found.", 404); return res.json({ education_video: publicVideo(row, true) }); }
async function listAdminVideos(req, res) { const rows = await EducationVideo.find(req.query.category ? { category: String(req.query.category).trim() } : {}).sort({ created_at: -1 }); return res.json({ education_videos: rows.map((item) => publicVideo(item, true, true)) }); }

function verifyUpload(upload) {
  const folder = "penmozhi/education/videos";
  if (!upload || typeof upload !== "object" || !upload.public_id || !upload.secure_url || !String(upload.public_id).startsWith(`${folder}/`)) return null;
  const url = new URL(String(upload.secure_url));
  if (url.protocol !== "https:" || url.hostname !== "res.cloudinary.com" || upload.resource_type !== "video") return null;
  const bytes = Number(upload.bytes); const version = Number(upload.version);
  if (!Number.isFinite(bytes) || bytes < 1 || bytes > 200 * 1024 * 1024 || !Number.isFinite(version)) return null;
  if (!upload.signature || !config.cloudinaryApiSecret) return null;
  const expected = crypto.createHash("sha1").update(`public_id=${upload.public_id}&version=${version}${config.cloudinaryApiSecret}`).digest("hex");
  if (expected !== upload.signature) return null;
  return { public_id: String(upload.public_id), secure_url: String(upload.secure_url), thumbnail_url: upload.thumbnail_url || `https://res.cloudinary.com/${config.cloudinaryCloudName}/video/upload/so_0/${upload.public_id}.jpg` };
}
async function uploadSignature(req, res) { if (!config.cloudinaryCloudName || !config.cloudinaryApiKey || !config.cloudinaryApiSecret) return errorResponse(res, "education.cloudinary_not_configured", "Cloudinary is not configured.", 503); const timestamp = Math.floor(Date.now() / 1000); const folder = "penmozhi/education/videos"; const signature = crypto.createHash("sha1").update(`folder=${folder}&timestamp=${timestamp}${config.cloudinaryApiSecret}`).digest("hex"); return res.json({ upload: { cloud_name: config.cloudinaryCloudName, api_key: config.cloudinaryApiKey, timestamp, folder, signature } }); }
async function createVideo(req, res) { const data = req.body || {}; const upload = verifyUpload(data.upload); const errors = []; if (!String(data.title || "").trim()) errors.push(["validation.title_required", "title is required."]); if (!String(data.category || "").trim()) errors.push(["validation.category_required", "category is required."]); if (!upload) errors.push(["validation.video_invalid", "A completed Cloudinary video upload is required."]); if (errors.length) return validationErrors(res, errors); const row = await EducationVideo.create({ title: String(data.title).trim(), description: data.description ? String(data.description).trim() : null, video_url: upload.secure_url, video_public_id: upload.public_id, thumbnail_url: upload.thumbnail_url, category: String(data.category).trim(), created_by_admin_id: req.user.id }); return messageResponse(res, "education.video_entry_created", "Education video created successfully.", 201, { education_video: publicVideo(row, true, true) }); }
async function updateVideo(req, res) { const row = await EducationVideo.findOne({ id: Number(req.params.video_id) }); if (!row) return errorResponse(res, "education.video_entry_not_found", "Education video not found.", 404); if (req.body.title !== undefined) row.title = String(req.body.title).trim(); if (req.body.description !== undefined) row.description = req.body.description ? String(req.body.description).trim() : null; if (req.body.category !== undefined) row.category = String(req.body.category).trim(); row.updated_at = new Date(); await row.save(); return messageResponse(res, "education.video_entry_updated", "Education video updated successfully.", 200, { education_video: publicVideo(row, true, true) }); }
async function deleteVideo(req, res) { const row = await EducationVideo.findOne({ id: Number(req.params.video_id) }); if (!row) return errorResponse(res, "education.video_entry_not_found", "Education video not found.", 404); await row.deleteOne(); return messageResponse(res, "education.video_entry_deleted", "Education video deleted successfully."); }
async function uploadArticleVideo(req, res) { const row = await EducationalResource.findOne({ id: Number(req.params.article_id) }); if (!row) return errorResponse(res, "education.not_found", "Educational resource not found.", 404); const upload = verifyUpload(req.body?.upload); if (!upload) return validationErrors(res, [["validation.video_invalid", "A completed Cloudinary video upload is required."]]); row.video_url = upload.secure_url; row.video_public_id = upload.public_id; await row.save(); return messageResponse(res, "education.video_uploaded", "Video uploaded successfully.", 200, { education_resource: serialize(row, ["publication_date", "created_at"]) }); }
async function deleteArticleVideo(req, res) { const row = await EducationalResource.findOne({ id: Number(req.params.article_id) }); if (!row) return errorResponse(res, "education.not_found", "Educational resource not found.", 404); if (!row.video_url && !row.video_public_id) return errorResponse(res, "education.video_not_found", "This article has no video.", 404); row.video_url = null; row.video_public_id = null; await row.save(); return messageResponse(res, "education.video_removed", "Video removed successfully.", 200, { education_resource: serialize(row, ["publication_date", "created_at"]) }); }

function forumPayload(post, comments = false) { const result = serialize(post, ["posted_at", "created_at"]); result.profile_id = null; result.author_display = "Anonymous"; if (comments) result.comments = []; return result; }
async function forumPosts(req, res) { const rows = await ForumPost.find().sort({ posted_at: -1 }); return res.json({ forum_posts: rows.map((item) => forumPayload(item)) }); }
async function forumPost(req, res) { const row = await ForumPost.findOne({ id: Number(req.params.post_id) }); if (!row) return errorResponse(res, "forum.post_not_found", "Forum post not found.", 404); const result = forumPayload(row, true); result.comments = (await ForumComment.find({ post_id: row.id }).sort({ posted_at: 1 })).map((comment) => { const value = serialize(comment, ["posted_at", "created_at"]); value.profile_id = null; value.author_display = "Anonymous"; return value; }); return res.json({ forum_post: result }); }
async function createForumPost(req, res) { const data = req.body || {}; if (!String(data.title || "").trim() || !String(data.body || "").trim()) return validationErrors(res, [["validation.invalid_payload", "title and body are required."]]); if (data.content_id && !await EducationalResource.exists({ id: Number(data.content_id) })) return validationErrors(res, [["validation.invalid_payload", "content_id references an educational resource that does not exist."]]); const row = await ForumPost.create({ profile_id: req.user.id, content_id: data.content_id ? Number(data.content_id) : null, title: String(data.title).trim(), body: String(data.body).trim() }); return messageResponse(res, "forum.post_created", "Forum post created successfully.", 201, { forum_post: forumPayload(row) }); }
async function updateForumPost(req, res) { const row = await ForumPost.findOne({ id: Number(req.params.post_id) }); if (!row) return errorResponse(res, "forum.post_not_found", "Forum post not found.", 404); if (row.profile_id !== req.user.id) return errorResponse(res, "auth.forbidden", "Access forbidden: insufficient permissions.", 403); for (const key of ["title", "body"]) if (req.body[key] !== undefined) row[key] = String(req.body[key]).trim(); if (req.body.content_id !== undefined) row.content_id = req.body.content_id ? Number(req.body.content_id) : null; await row.save(); return messageResponse(res, "forum.post_updated", "Forum post updated successfully.", 200, { forum_post: forumPayload(row) }); }
async function deleteForumPost(req, res) { const row = await ForumPost.findOne({ id: Number(req.params.post_id) }); if (!row) return errorResponse(res, "forum.post_not_found", "Forum post not found.", 404); if (row.profile_id !== req.user.id && req.user.role !== "admin") return errorResponse(res, "auth.forbidden", "Access forbidden: insufficient permissions.", 403); await ForumComment.deleteMany({ post_id: row.id }); await row.deleteOne(); return messageResponse(res, "forum.post_deleted", "Forum post deleted successfully."); }
async function createForumComment(req, res) { const post = await ForumPost.findOne({ id: Number(req.params.post_id) }); if (!post) return errorResponse(res, "forum.post_not_found", "Forum post not found.", 404); if (!String(req.body?.body || "").trim()) return validationErrors(res, [["validation.body_required", "body is required."]]); const row = await ForumComment.create({ post_id: post.id, profile_id: req.user.id, body: String(req.body.body).trim() }); const result = serialize(row, ["posted_at", "created_at"]); result.profile_id = null; result.author_display = "Anonymous"; return messageResponse(res, "forum.comment_created", "Comment created successfully.", 201, { forum_comment: result }); }

module.exports = { createEducation, createForumComment, createForumPost, createVideo, deleteArticleVideo, deleteEducation, deleteForumPost, deleteVideo, forumPost, forumPosts, getEducation, getVideo, listAdminVideos, listEducation, listVideos, updateEducation, updateForumPost, updateVideo, uploadArticleVideo, uploadSignature };
